spec:
  inputs:
    tags:
      default: amd64
---

distribute:
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
    RUNNER_TAGS: test
  stage: distribute
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  tags:
    - $[[ inputs.tags ]]
  script:
    - find .gitlab-ci/artifacts/${CI_COMMIT_SHA} -type f
    - |+
      if [ -d .gitlab-ci/artifacts/${CI_COMMIT_SHA} ]; then
        pushd .gitlab-ci/artifacts/${CI_COMMIT_SHA}
        mv -v *.img.gz /mnt/apt/aptly/public/images
        popd
      fi
